"""Signal Registry for the TradingAgents Research Factory.

The signal registry is the persistent store of all signals generated by
the agent pipeline. It records:
- The raw signal (direction, conviction, entry, stop, target)
- Which agent roles contributed and their individual scores
- The outcome (actual return, hit rate) once the horizon passes
- Performance metrics for walk-forward evaluation

Storage: SQLite (local dev) or Parquet (production).
The registry is append-only — signals are never overwritten, only updated
with outcome data once the horizon has elapsed.
"""
from __future__ import annotations

import json
import logging
import sqlite3
from dataclasses import asdict, dataclass, field
from datetime import datetime, date
from enum import Enum
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import pandas as pd

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Signal record
# ---------------------------------------------------------------------------

class SignalDirection(str, Enum):
    LONG = "long"
    SHORT = "short"
    FLAT = "flat"


class SignalStatus(str, Enum):
    OPEN = "open"          # Horizon not yet elapsed
    CLOSED = "closed"      # Outcome recorded
    CANCELLED = "cancelled"  # Signal invalidated before horizon


@dataclass
class SignalRecord:
    """A single signal record in the registry."""
    # Identity
    signal_id: str               # UUID
    ticker: str
    trade_date: str              # YYYY-MM-DD
    pipeline_version: str        # e.g. "0.2.4"

    # Signal
    direction: SignalDirection
    conviction: float            # 0.0 to 1.0
    target_horizon_days: int     # e.g. 45
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    max_position_pct: float = 0.02

    # Agent context
    agent_config_id: Optional[str] = None    # Which agent config generated this
    active_roles: List[str] = field(default_factory=list)
    role_scores: Dict[str, float] = field(default_factory=dict)  # role -> composite score
    ensemble_score: float = 0.0
    debate_winner: Optional[str] = None      # "bull" or "bear"

    # Thesis summary
    executive_summary: str = ""
    investment_thesis: str = ""
    invalidation_condition: str = ""

    # Outcome (filled in after horizon)
    status: SignalStatus = SignalStatus.OPEN
    exit_date: Optional[str] = None
    exit_price: Optional[float] = None
    actual_return: Optional[float] = None    # (exit - entry) / entry
    hit_target: Optional[bool] = None        # Did price reach take_profit?
    hit_stop: Optional[bool] = None          # Did price hit stop_loss?
    outcome_notes: str = ""

    # Metadata
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    updated_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())


# ---------------------------------------------------------------------------
# Signal Registry
# ---------------------------------------------------------------------------

class SignalRegistry:
    """Persistent signal registry backed by SQLite.

    Usage:
        registry = SignalRegistry("data/signals.db")

        # Save a signal
        registry.save(signal_record)

        # Query open signals
        open_signals = registry.get_open_signals("AAPL")

        # Update outcome
        registry.record_outcome(signal_id, exit_price, exit_date)

        # Get performance metrics
        metrics = registry.compute_metrics("AAPL")
    """

    CREATE_TABLE_SQL = """
    CREATE TABLE IF NOT EXISTS signals (
        signal_id TEXT PRIMARY KEY,
        ticker TEXT NOT NULL,
        trade_date TEXT NOT NULL,
        pipeline_version TEXT,
        direction TEXT NOT NULL,
        conviction REAL,
        target_horizon_days INTEGER,
        entry_price REAL,
        stop_loss REAL,
        take_profit REAL,
        max_position_pct REAL,
        agent_config_id TEXT,
        active_roles TEXT,        -- JSON array
        role_scores TEXT,         -- JSON object
        ensemble_score REAL,
        debate_winner TEXT,
        executive_summary TEXT,
        investment_thesis TEXT,
        invalidation_condition TEXT,
        status TEXT DEFAULT 'open',
        exit_date TEXT,
        exit_price REAL,
        actual_return REAL,
        hit_target INTEGER,
        hit_stop INTEGER,
        outcome_notes TEXT,
        created_at TEXT,
        updated_at TEXT
    );
    CREATE INDEX IF NOT EXISTS idx_signals_ticker ON signals(ticker);
    CREATE INDEX IF NOT EXISTS idx_signals_trade_date ON signals(trade_date);
    CREATE INDEX IF NOT EXISTS idx_signals_status ON signals(status);
    """

    def __init__(self, db_path: str = "data/signals.db"):
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._init_db()

    def _connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(str(self.db_path))
        conn.row_factory = sqlite3.Row
        return conn

    def _init_db(self):
        with self._connect() as conn:
            for stmt in self.CREATE_TABLE_SQL.strip().split(";"):
                stmt = stmt.strip()
                if stmt:
                    conn.execute(stmt)
            conn.commit()

    # ------------------------------------------------------------------
    # Write operations
    # ------------------------------------------------------------------

    def save(self, signal: SignalRecord) -> bool:
        """Insert or replace a signal record."""
        row = {
            "signal_id": signal.signal_id,
            "ticker": signal.ticker.upper(),
            "trade_date": signal.trade_date,
            "pipeline_version": signal.pipeline_version,
            "direction": signal.direction.value if isinstance(signal.direction, SignalDirection) else signal.direction,
            "conviction": signal.conviction,
            "target_horizon_days": signal.target_horizon_days,
            "entry_price": signal.entry_price,
            "stop_loss": signal.stop_loss,
            "take_profit": signal.take_profit,
            "max_position_pct": signal.max_position_pct,
            "agent_config_id": signal.agent_config_id,
            "active_roles": json.dumps(signal.active_roles),
            "role_scores": json.dumps(signal.role_scores),
            "ensemble_score": signal.ensemble_score,
            "debate_winner": signal.debate_winner,
            "executive_summary": signal.executive_summary,
            "investment_thesis": signal.investment_thesis,
            "invalidation_condition": signal.invalidation_condition,
            "status": signal.status.value if isinstance(signal.status, SignalStatus) else signal.status,
            "exit_date": signal.exit_date,
            "exit_price": signal.exit_price,
            "actual_return": signal.actual_return,
            "hit_target": int(signal.hit_target) if signal.hit_target is not None else None,
            "hit_stop": int(signal.hit_stop) if signal.hit_stop is not None else None,
            "outcome_notes": signal.outcome_notes,
            "created_at": signal.created_at,
            "updated_at": datetime.utcnow().isoformat(),
        }
        cols = ", ".join(row.keys())
        placeholders = ", ".join("?" * len(row))
        sql = f"INSERT OR REPLACE INTO signals ({cols}) VALUES ({placeholders})"
        try:
            with self._connect() as conn:
                conn.execute(sql, list(row.values()))
                conn.commit()
            return True
        except Exception as e:
            logger.error(f"Failed to save signal {signal.signal_id}: {e}")
            return False

    def record_outcome(
        self,
        signal_id: str,
        exit_price: float,
        exit_date: str,
        outcome_notes: str = "",
    ) -> bool:
        """Record the outcome of a signal after the horizon has elapsed."""
        # First fetch the signal to compute actual_return
        signal = self.get(signal_id)
        if signal is None:
            logger.error(f"Signal {signal_id} not found")
            return False

        actual_return = None
        hit_target = None
        hit_stop = None

        if signal.entry_price and signal.entry_price > 0:
            actual_return = (exit_price - signal.entry_price) / signal.entry_price
            if signal.direction == SignalDirection.SHORT:
                actual_return = -actual_return

        if signal.take_profit and signal.entry_price:
            hit_target = exit_price >= signal.take_profit if signal.direction == SignalDirection.LONG else exit_price <= signal.take_profit

        if signal.stop_loss and signal.entry_price:
            hit_stop = exit_price <= signal.stop_loss if signal.direction == SignalDirection.LONG else exit_price >= signal.stop_loss

        sql = """
            UPDATE signals SET
                status = 'closed',
                exit_date = ?,
                exit_price = ?,
                actual_return = ?,
                hit_target = ?,
                hit_stop = ?,
                outcome_notes = ?,
                updated_at = ?
            WHERE signal_id = ?
        """
        try:
            with self._connect() as conn:
                conn.execute(sql, [
                    exit_date, exit_price, actual_return,
                    int(hit_target) if hit_target is not None else None,
                    int(hit_stop) if hit_stop is not None else None,
                    outcome_notes, datetime.utcnow().isoformat(), signal_id,
                ])
                conn.commit()
            return True
        except Exception as e:
            logger.error(f"Failed to record outcome for {signal_id}: {e}")
            return False

    # ------------------------------------------------------------------
    # Read operations
    # ------------------------------------------------------------------

    def get(self, signal_id: str) -> Optional[SignalRecord]:
        """Fetch a single signal by ID."""
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM signals WHERE signal_id = ?", [signal_id]
            ).fetchone()
        if row is None:
            return None
        return self._row_to_record(dict(row))

    def get_open_signals(self, ticker: Optional[str] = None) -> List[SignalRecord]:
        """Get all open signals, optionally filtered by ticker."""
        if ticker:
            sql = "SELECT * FROM signals WHERE status = 'open' AND ticker = ? ORDER BY trade_date DESC"
            params = [ticker.upper()]
        else:
            sql = "SELECT * FROM signals WHERE status = 'open' ORDER BY trade_date DESC"
            params = []
        with self._connect() as conn:
            rows = conn.execute(sql, params).fetchall()
        return [self._row_to_record(dict(r)) for r in rows]

    def get_closed_signals(
        self,
        ticker: Optional[str] = None,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
    ) -> List[SignalRecord]:
        """Get closed signals with optional filters."""
        conditions = ["status = 'closed'"]
        params = []
        if ticker:
            conditions.append("ticker = ?")
            params.append(ticker.upper())
        if start_date:
            conditions.append("trade_date >= ?")
            params.append(start_date)
        if end_date:
            conditions.append("trade_date <= ?")
            params.append(end_date)
        sql = f"SELECT * FROM signals WHERE {' AND '.join(conditions)} ORDER BY trade_date DESC"
        with self._connect() as conn:
            rows = conn.execute(sql, params).fetchall()
        return [self._row_to_record(dict(r)) for r in rows]

    def to_dataframe(
        self,
        ticker: Optional[str] = None,
        status: Optional[str] = None,
    ) -> pd.DataFrame:
        """Return signals as a DataFrame for analysis."""
        conditions = []
        params = []
        if ticker:
            conditions.append("ticker = ?")
            params.append(ticker.upper())
        if status:
            conditions.append("status = ?")
            params.append(status)
        where = f"WHERE {' AND '.join(conditions)}" if conditions else ""
        sql = f"SELECT * FROM signals {where} ORDER BY trade_date DESC"
        with self._connect() as conn:
            return pd.read_sql_query(sql, conn, params=params)

    # ------------------------------------------------------------------
    # Performance metrics
    # ------------------------------------------------------------------

    def compute_metrics(
        self,
        ticker: Optional[str] = None,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
    ) -> Dict:
        """Compute performance metrics for closed signals.

        Returns:
            Dict with: total_signals, win_rate, avg_return, sharpe_proxy,
            max_drawdown, hit_target_rate, hit_stop_rate, by_direction.
        """
        signals = self.get_closed_signals(ticker, start_date, end_date)
        if not signals:
            return {"total_signals": 0, "message": "No closed signals found"}

        returns = [s.actual_return for s in signals if s.actual_return is not None]
        if not returns:
            return {"total_signals": len(signals), "message": "No outcomes recorded"}

        returns_arr = pd.Series(returns)
        wins = (returns_arr > 0).sum()
        losses = (returns_arr <= 0).sum()

        # Sharpe proxy (no risk-free rate, using signal returns directly)
        sharpe = (returns_arr.mean() / returns_arr.std()) if returns_arr.std() > 0 else 0.0

        # Max drawdown proxy (cumulative returns)
        cum_returns = (1 + returns_arr).cumprod()
        rolling_max = cum_returns.cummax()
        drawdowns = (cum_returns - rolling_max) / rolling_max
        max_drawdown = drawdowns.min()

        hit_targets = [s.hit_target for s in signals if s.hit_target is not None]
        hit_stops = [s.hit_stop for s in signals if s.hit_stop is not None]

        # By direction
        long_returns = [s.actual_return for s in signals
                        if s.direction == SignalDirection.LONG and s.actual_return is not None]
        short_returns = [s.actual_return for s in signals
                         if s.direction == SignalDirection.SHORT and s.actual_return is not None]

        return {
            "total_signals": len(signals),
            "closed_with_returns": len(returns),
            "win_rate": round(wins / len(returns), 3) if returns else 0,
            "avg_return": round(returns_arr.mean(), 4),
            "median_return": round(returns_arr.median(), 4),
            "std_return": round(returns_arr.std(), 4),
            "sharpe_proxy": round(sharpe, 3),
            "max_drawdown": round(max_drawdown, 4),
            "hit_target_rate": round(sum(hit_targets) / len(hit_targets), 3) if hit_targets else None,
            "hit_stop_rate": round(sum(hit_stops) / len(hit_stops), 3) if hit_stops else None,
            "by_direction": {
                "long": {
                    "count": len(long_returns),
                    "avg_return": round(pd.Series(long_returns).mean(), 4) if long_returns else None,
                },
                "short": {
                    "count": len(short_returns),
                    "avg_return": round(pd.Series(short_returns).mean(), 4) if short_returns else None,
                },
            },
            "ticker": ticker or "all",
            "period": f"{start_date or 'all'} to {end_date or 'now'}",
        }

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _row_to_record(self, row: dict) -> SignalRecord:
        """Convert a DB row dict to a SignalRecord."""
        row["active_roles"] = json.loads(row.get("active_roles") or "[]")
        row["role_scores"] = json.loads(row.get("role_scores") or "{}")
        row["direction"] = SignalDirection(row["direction"])
        row["status"] = SignalStatus(row["status"])
        row["hit_target"] = bool(row["hit_target"]) if row.get("hit_target") is not None else None
        row["hit_stop"] = bool(row["hit_stop"]) if row.get("hit_stop") is not None else None
        return SignalRecord(**{k: v for k, v in row.items() if k in SignalRecord.__dataclass_fields__})

    def count(self) -> int:
        """Return total number of signals in the registry."""
        with self._connect() as conn:
            return conn.execute("SELECT COUNT(*) FROM signals").fetchone()[0]
